Web_Client/Controllers/ServicesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using CRM_Helper;
using CRM_APIRequests;
using Web_Client.Models;

namespace Web_Client.Controllers
{
	public class ServicesController : Controller
	{
		private readonly SkillProfiWebClient _spClient = new();

		public async Task<IActionResult> Services()
		{
			return View(await _spClient.Services.GetListAsync());
		}

		[Authorize]
		[HttpGet]
		public async Task<IActionResult> EditAsync(string? id)
		{
			if (id == null)
                return View(new ModelCustom<ServiceTransfer>() { Target = new ()});
            

			Service service = await _spClient.Services.GetByIdAsync(id);

			ModelCustom<ServiceTransfer> mc = new()
			{
				Id = service.Id.ToString(),
				Target = new()
				{
					Description = service.Description,
					Title = service.Title,
				}
			};
			return View(mc);
		}


        [Authorize]
		[HttpPost]
		public async Task<IActionResult> EditAsync(ModelCustom<ServiceTransfer> model, string? id)
		{
			if (!ModelState.IsValid)
				return View(model);

			ServiceTransfer st = model.Target;
			if (id != null)
			{
				await _spClient.Services.EditAsync(id, st);

			}
			else
			{
                await _spClient.Services.AddAsync(st);
            }
			
			return Redirect("~/Services/Services");
		}
		
		[Authorize]
		[HttpGet]
		public async Task<IActionResult> DeleteAsync(string id)
		{
            await _spClient.Services.DeleteByIdAsync(id);
			return Redirect("~/Services/Services");

        }

	}
}

Web_Client/Views/Services/Edit.cshtml
@model ModelCustom<ServiceTransfer>

@{
    ViewData["Title"] = "Edit";
}

@using (Html.BeginForm("Edit","Services", FormMethod.Post))
{

    Html.AntiForgeryToken();
    Html.HiddenFor(model => model.Id);
    @Html.HiddenFor(model => model.ImageLink);

    <div>
        @Html.EditorFor(model => model.Target.Title, new
        {
            htmlAttributes = new
            {
                @placeholder = "Заголовок"
            }
        })

        @Html.ValidationMessageFor(model => model.Target.Title, "", new { @class = "error-text" })
    </div>

    <div>

        @Html.EditorFor(model => model.Target.Description, new
        {
            htmlAttributes = new
            {   
                @placeholder = "Описание",
                @class = "textarea-input"
            }
        })
        @Html.ValidationMessageFor(model => model.Target.Description, "", new { @class = "error-text" })
    </div>

    <input type="submit"  style="float:right;" value="Отправить" class="button" />
}

<input
    type="button"
    class="button" style="float: right;" 
    onclick="@("window.location.href='" + Url.Action("Services") + "'");" value="Назад">

Web_Client/Views/Services/Services.cshtml
@model List<Service>

@{
    ViewData["Title"] = "Services";
}

<div class="title">
    <p>Сервисы, которые мы предлагаем:</p>
</div>

@if(User.Identity != null && User.Identity.IsAuthenticated)
{
    <div class="block-nav">
        <input 
            type="submit" value="Добавить" 
            onclick="@("window.location.href='" + Url.Action("Edit") + "'");"
            class="mini-button"/>
    </div>
}


<div id="toggle-list" class="toggle-list">

    @{
    foreach (var srvc in Model)
    {
        <div id="@srvc.Id" class="toggle">

            <div class="toggle-title">
                <p>@srvc.Title</p>
            </div>

            <div class="toggle-context">
                <p>@srvc.Description</p>

                @if (User.Identity != null && User.Identity.IsAuthenticated)
                {
                    <div class="block-nav" style="justify-content: right;">

                        <input 
                            type="button" value="Редактировать" 
                            onclick="@("window.location.href='" + @Url.Action("Edit", new { id = srvc.Id}) + "'")"
                            class="mini-button"/>
            
                        <input 
                            type="button" value="Удалить" 
                            onclick="@("window.location.href='" + @Url.Action("Delete", new { id = srvc.Id}) + "'")"
                            class="mini-button"/>
            
                    </div>
                }
            </div>
        </div>                  
       
    }
    }  
    <script>
        const accordion = document.getElementsByClassName('toggle')
        for (i = 0; i < accordion.length; i++) {

            let toggleTitle = accordion[i].getElementsByClassName("toggle-title")[0]

            toggleTitle.addEventListener('click', function() {
                this.parentNode.classList.toggle('active')
            })
        }
    </script>
</div>